name: "Parse and upload metrics"
description: "Parses and uploads GitHub actions workflow metrics to Azure Monitor"
author: "Credera UK"
inputs:
  name:
    description: "Name of the workflow which 'data' relates to"
    required: true
  data:
    description: "JSON data returned from the GitHub ' List jobs for a workflow run' endpoint"
    required: true
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: bar-chart-2
  color: blue
